language: cpp

sudo: enabled

compiler:
  - gcc

matrix:
  include:
    - os: linux
      name: Ubuntu 16.04
      dist: xenial
    - os: linux
      name: Ubuntu 18.04
      dist: bionic
    - os: osx
      name: OSX
      env:
      - CC=gcc-9
      - CXX=g++-9
      - AR=g++-9

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install ocl-icd-libopencl1 opencl-headers ocl-icd-opencl-dev; fi

addons:
  apt:
    packages:
    - ocl-icd-libopencl1
    - opencl-headers
    - ocl-icd-opencl-dev
    update: true

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
         make -C src;
      else
         find /usr -name libgomp.a ;
         make -C src AR=g++-9 CC=gcc-9 CXX=g++-9;
      fi
